import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import agentsRouter from "./agents";
import settingsRouter from "./settings";
import salesRouter from "./sales";
import entriesRouter from "./entries";
import paymentsRouter from "./payments";
import calculationsRouter from "./calculations";
import reportsRouter from "./reports";
import reserveRouter from "./reserve";
import notificationsRouter from "./notifications";
import gamesRouter from "./games";
import gameTemplatesRouter from "./game-templates";
import recurringExpensesRouter from "./recurring-expenses";
import companyExpensesRouter from "./company-expenses";
import entryChangeRequestsRouter from "./entry-change-requests";
import paystackRouter from "./paystack";
import agencyStaffRouter from "./agency-staff";
import companyStaffRouter from "./company-staff";
import staffPayrollRouter from "./staff-payroll";
import inventoryRouter from "./inventory";
import writerAuthRouter from "./writer-auth";
import betTypesRouter from "./bet-types";
import writerTicketsRouter from "./writer-tickets";
import writerTokensRouter from "./writer-tokens";
import gameResultsRouter from "./game-results";
import postpaidSettlementRouter from "./postpaid-settlement";
import riskManagementRouter from "./risk-management";
import hedgeSettingsRouter from "./hedge-settings";
import writerApprovalsRouter from "./writer-approvals";
import liveSalesRouter from "./live-sales";
import ticketReceiptsRouter from "./ticket-receipts";
import payoutApprovalsRouter from "./payout-approvals";
import dashboardSummaryRouter from "./dashboard-summary";
import writerTokenPurchasesRouter from "./writer-token-purchases";
import tokenSupplyRouter from "./token-supply";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(agencyStaffRouter);
router.use(agentsRouter);
router.use(settingsRouter);
router.use(salesRouter);
router.use(entriesRouter);
router.use(entryChangeRequestsRouter);
router.use(recurringExpensesRouter);
router.use(companyExpensesRouter);
router.use(paymentsRouter);
router.use(calculationsRouter);
router.use(reportsRouter);
router.use(reserveRouter);
router.use(notificationsRouter);
router.use(gamesRouter);
router.use(gameTemplatesRouter);
router.use(paystackRouter);
router.use(companyStaffRouter);
router.use(staffPayrollRouter);
router.use(inventoryRouter);
router.use(writerAuthRouter);
router.use(betTypesRouter);
router.use(writerTicketsRouter);
router.use(writerTokensRouter);
router.use(gameResultsRouter);
router.use(postpaidSettlementRouter);
router.use(riskManagementRouter);
router.use(hedgeSettingsRouter);
router.use(writerApprovalsRouter);
router.use(liveSalesRouter);
router.use(ticketReceiptsRouter);
router.use(payoutApprovalsRouter);
router.use(dashboardSummaryRouter);
router.use(writerTokenPurchasesRouter);
router.use(tokenSupplyRouter);

export default router;
